#https://github.com/eko/docker-symfony
#https://symfony.fi/entry/consider-docker-for-your-symfony-projects

version: '2'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./.docker/images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/logs/nginx/:/var/log/nginx
    links:
      - php
    volumes_from:
      - php
    depends_on:
      - php

  php:
    build: ./.docker/images/php-fpm
    environment:
      SYMFONY_ENV: dev
      XDEBUG_CONFIG: "remote_host=${REMOTE_HOST}"
      PHP_IDE_CONFIG: "serverName=${SERVER_NAME}"
    links:
      - db
    volumes:
      - .:/var/www/html
      - ./.docker/images/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - ./.docker/data/db:/var/lib/mysql
      - ./.docker/data/dumps:/docker-entrypoint-initdb.d
      - ./.docker/images/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
